#!/bin/bash
# Re-clones all tmux plugins listed in tmux.conf.
# The pre-commit hook strips .git dirs on commit.

repo_dir="$(cd "$(dirname "$0")" && pwd)"
plugin_dir="$repo_dir/tmux/tmux/plugins"
tmux_conf="$repo_dir/tmux/tmux.conf"

grep -oP "set -g @plugin '\K[^']+" "$tmux_conf" | while read -r plugin; do
    name=$(basename "$plugin")
    echo "Updating $plugin..."
    rm -rf "${plugin_dir:?}/$name"
    git clone --depth 1 "https://github.com/$plugin.git" "$plugin_dir/$name"
done
