#Requires AutoHotkey v2.0
#SingleInstance Force
SetTitleMatchMode("Slow")
InstallMouseHook()
InstallKeybdHook()

; Don't flood windows with gui events too fast
SetMouseDelay(10)

g_vpn_autologin_enabled := true

; Keep the generated include list in sync with enabled repo and custom plugins.
if (RefreshPluginIncludes())
    Reload

Return  ; End of auto-execute section

; ^ = Ctrl
; + = Shift
; ! = Alt

; If you make any edits to this file, do a ctrl-alt-r to reload the script
^!r::
{
    Reload
}

; Toggle all hotkeys on/off — exempt from suspension so it always works.
#SuspendExempt
^!a::
{
    Suspend(-1)
    if (A_IsSuspended) {
        ToolTip("Hotkeys: PAUSED")
    } else {
        ToolTip("Hotkeys: ACTIVE")
    }
    SetTimer(() => ToolTip(), -1000)
}
#SuspendExempt False

; VPN auto-login toggle (implemented by 30-cisco-secure-client-vpn plugin).
$^!v::
{
    global g_vpn_autologin_enabled
    g_vpn_autologin_enabled := !g_vpn_autologin_enabled
    state := g_vpn_autologin_enabled ? "ON" : "OFF"
    ToolTip("VPN auto-login: " state)
    SetTimer(() => ToolTip(), -1000)
}

; Auto-generated include file with one #Include per enabled plugin file.
#Include *i %A_ScriptDir%\_autoload_plugins.generated.ahk

RefreshPluginIncludes()
{
    plugins_dir := A_ScriptDir . "\\plugins"
    custom_plugins_dir := A_ScriptDir . "\\custom_plugins"
    generated := A_ScriptDir . "\\_autoload_plugins.generated.ahk"

    if !DirExist(plugins_dir)
        DirCreate(plugins_dir)
    if !DirExist(custom_plugins_dir)
        DirCreate(custom_plugins_dir)

    plugin_files := []
    plugin_dirs := [plugins_dir, custom_plugins_dir]
    for plugin_dir in plugin_dirs {
        Loop Files, plugin_dir . "\\*.ahk", "F"
        {
            if (A_LoopFileName = "_autoload_plugins.generated.ahk")
                continue

            inserted := false
            for idx, existing_path in plugin_files {
                if (StrCompare(A_LoopFileFullPath, existing_path) < 0) {
                    plugin_files.InsertAt(idx, A_LoopFileFullPath)
                    inserted := true
                    break
                }
            }

            if !inserted
                plugin_files.Push(A_LoopFileFullPath)
        }
    }

    content := "; Auto-generated by hotkeys.ahk. Do not edit.`n"
    for plugin_path in plugin_files
        content .= "#Include *i " . Chr(34) . plugin_path . Chr(34) . "`n"

    existing := ""
    if FileExist(generated) {
        try existing := FileRead(generated, "UTF-8")
    }

    if (existing = content)
        return false

    try FileDelete(generated)
    FileAppend(content, generated, "UTF-8")
    return true
}
