param(
    [string]$CorpUid = 'dummy.uid',
    [string]$CorpPassword = 'dummy.corp.password',
    [string]$PwManagerPassword = 'dummy.pwmanager.password',
    [switch]$KeepOpen
)

$ErrorActionPreference = 'Stop'

$scriptPath = Join-Path $PSScriptRoot 'hotkeys.ahk'
if (-not (Test-Path $scriptPath)) {
    throw "Could not find AutoHotkey script at: $scriptPath"
}

$repoPluginsDir = Join-Path $PSScriptRoot 'plugins'
if (-not (Test-Path $repoPluginsDir -PathType Container)) {
    throw "Could not find plugin directory at: $repoPluginsDir"
}

$sandboxRoot = Join-Path $env:TEMP ("dotkeys-ahk-test-" + [guid]::NewGuid().ToString('N'))
$sandboxPluginsDir = Join-Path $sandboxRoot 'plugins'
$sandboxCustomPluginsDir = Join-Path $sandboxRoot 'custom_plugins'
$sandboxGeneratedIncludes = Join-Path $sandboxRoot '_autoload_plugins.generated.ahk'

New-Item -ItemType Directory -Path $sandboxPluginsDir -Force | Out-Null
New-Item -ItemType Directory -Path $sandboxCustomPluginsDir -Force | Out-Null

Copy-Item -Path $scriptPath -Destination (Join-Path $sandboxRoot 'hotkeys.ahk') -Force

@(
    '; Auto-generated by test-run.ps1. Do not edit.'
) | Set-Content -Path $sandboxGeneratedIncludes -Encoding UTF8

$enabledPluginPaths = @()

Get-ChildItem -Path $repoPluginsDir -File -ErrorAction Stop | ForEach-Object {
    if ($_.Name -ceq '_autoload_plugins.generated.ahk') {
        return
    }

    if ($_.Name -cmatch '\.ahk\.disabled$') {
        $enabledName = [System.IO.Path]::GetFileNameWithoutExtension($_.Name)
        $destPath = Join-Path $sandboxPluginsDir $enabledName
        Copy-Item -Path $_.FullName -Destination $destPath -Force
        $enabledPluginPaths += $destPath
        return
    }

    if ($_.Name -cmatch '\.ahk$') {
        $destPath = Join-Path $sandboxPluginsDir $_.Name
        Copy-Item -Path $_.FullName -Destination $destPath -Force
        $enabledPluginPaths += $destPath
    }
}

$enabledPluginPaths = @($enabledPluginPaths | Sort-Object)
foreach ($pluginPath in $enabledPluginPaths) {
    Add-Content -Path $sandboxGeneratedIncludes -Value ('#Include *i "' + $pluginPath + '"') -Encoding UTF8
}

$scriptPath = Join-Path $sandboxRoot 'hotkeys.ahk'

$ahkInstallDirs = @()
try {
    $ahkInstallDirs = Get-ChildItem -Path $env:USERPROFILE -Directory -Filter 'AutoHotkey_*' -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending |
        Select-Object -ExpandProperty FullName
} catch {
    $ahkInstallDirs = @()
}

$ahkCandidates = @(
    (Get-Command 'AutoHotkey64.exe' -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source),
    (Get-Command 'AutoHotkey.exe' -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source),
    "$env:USERPROFILE\AutoHotkey_v2\AutoHotkey64.exe",
    "$env:USERPROFILE\AutoHotkey_v2\AutoHotkey.exe"
)

foreach ($dir in $ahkInstallDirs) {
    $ahkCandidates += (Join-Path $dir 'AutoHotkey64.exe')
    $ahkCandidates += (Join-Path $dir 'AutoHotkey.exe')
}

$ahkCandidates = $ahkCandidates |
    Where-Object { $_ -and (Test-Path $_) } |
    Select-Object -Unique

if (-not $ahkCandidates) {
    throw 'AutoHotkey executable not found. Install AutoHotkey v2 or add AutoHotkey64.exe to PATH.'
}

$ahkExe = @($ahkCandidates)[0]

$testEnv = @{
    CORP_UID = $CorpUid
    CORP_PASSWORD = $CorpPassword
    PWMANAGER_PASSWORD = $PwManagerPassword
    AHK_ENABLE_MOUSE_WIGGLE = 'true'
}

foreach ($kv in $testEnv.GetEnumerator()) {
    Set-Item -Path ("Env:" + $kv.Key) -Value $kv.Value
}

Write-Host 'Launching hotkeys.ahk with test environment variables:'
Write-Host "  CORP_UID=$($testEnv.CORP_UID)"
Write-Host "  CORP_PASSWORD=$($testEnv.CORP_PASSWORD)"
Write-Host "  PWMANAGER_PASSWORD=$($testEnv.PWMANAGER_PASSWORD)"
Write-Host "  AHK_ENABLE_MOUSE_WIGGLE=$($testEnv.AHK_ENABLE_MOUSE_WIGGLE)"
Write-Host "  Test sandbox=$sandboxRoot"
Write-Host '  Plugin mode=all repo plugins enabled, user custom_plugins excluded'
Write-Host "  Loaded plugins=$($enabledPluginPaths.Count)"
foreach ($pluginPath in $enabledPluginPaths) {
    Write-Host "    - $(Split-Path $pluginPath -Leaf)"
}

$psi = New-Object System.Diagnostics.ProcessStartInfo
$psi.FileName = $ahkExe
$psi.Arguments = '"' + $scriptPath + '"'
$psi.WorkingDirectory = $sandboxRoot
$psi.UseShellExecute = $false

foreach ($kv in $testEnv.GetEnumerator()) {
    $psi.EnvironmentVariables[$kv.Key] = $kv.Value
}

[void][System.Diagnostics.Process]::Start($psi)

if ($KeepOpen) {
    Write-Host ''
    Write-Host 'Press Enter to exit this shell (AHK keeps running in its own process).'
    Read-Host | Out-Null
}
